// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<YOUR REGION>",
    "aws_cognito_identity_pool_id": "<YOUR IDENTITIES POOL ID>",
    "aws_cognito_region": "<YOUR REGION>",
    "aws_user_pools_id": "<YOUR POOLS ID>",
    "aws_user_pools_web_client_id": "<YOUR POOLS WEB CLIENT ID>",
    "oauth": {
        "domain": "<YOUR DOMAIN>",
        "scope": [
            "email",
            "openid",
            "profile",
        ],
        "redirectSignIn": "<YOUR SIGNIN REDIRECT ADDRESS>",
        "redirectSignOut": "<YOUR SIGNOUT REDIRECT ADDRESS>",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;